import hahha from "../assets/beauty-woman-swing-bali-nature-happy-face-jungle.jpg";

export default function HowToPrompt() {
  return (
    <>
      <div className="w-[90%] h-full bg-white ml-[5%]">
        <div className="w-full h-[20%] flex mt-8 px-[4%] mb-8">
          <div className="w-[40%] h-full pl-4 pt-3">
            <p className="text-1xl text-slate-400">Special Features</p>
            <p className="text-5xl text-slate-700">Plan your trip With AI</p>
          </div>
          <div className=" w-[60%]  h-[60%] px-10 mt-9 text-slate-700 pt-3">
            Want to make your next trip easier and more enjoyable? We’ve got
            great news for you! 
            <p className="pt-1">
              {" "}
              Introducing AI Travel Planning – your smart personal assistant
              that will help you design your dream journey with ease!
            </p>
          </div>
        </div>
        <div className="flex justify-center gap-6 h-[80%] w-[70%] bg-slate-50 ml-[13%]">
          <div className="w-[50%] bg-white pt-2 relative">
            <img className="w-[98%] absolute h-[99%] rounded-2xl" src={hahha} />
            <div className=" absolute w-[98%] h-[3rem] backdrop-blur-md z-50 mt-[99%] flex items-center">
                <div className="h-full w-[25%] flex justify-center items-center text-slate-200">location</div>
                <div>|</div>
                <div className="h-full w-[25%]  flex justify-center items-center text-slate-200">Date</div>|
                <div className="h-full w-[25%]  flex justify-center items-center text-slate-200">Budget</div>|
                <div className="h-full w-[25%]  flex justify-center items-center">
                    <button className="w-[90%] h-[60%] bg-white rounded-3xl text-sm text-black">Search</button>
                </div>
            </div>
          </div>
          <div className="w-[50%] h-full bg-white grid grid-cols-1 px-4 py-4 pt-6">
            <div className="rounded-3xl h-[9vh] px-5 pt-2 shadow hover:scale-110 transition-transform">
              <div className="text-black text-[18px]" id="greeting">Input Your Preferences</div>
              <div className="text-sm">Start by entering your travel preferences into the AI tool.</div>
            </div>
            <div className=" rounded-3xl  h-[9vh] px-5 pt-2 shadow hover:scale-110 transition-transform">
            <div className="text-slate-700 text-[18px]" id="greeting">Discover Personalized Recommendations</div>
              <div className="text-sm text-slate-400">The AI will analyze your inputs and provide personalized recommendations for you</div>
            </div>
            <div className="rounded-3xl  h-[9vh] px-5 pt-2 shadow hover:scale-110 transition-transform">
            <div className="text-black text-[18px]" id="greeting">Review Suggested Itinerary</div>
              <div className="text-sm">Check the suggested itinerary generated by the AI.</div>
            </div>
            <div className=" rounded-3xl  h-[9vh] px-5 pt-2 shadow hover:scale-110 transition-transform">
            <div className="text-black text-[18px]" id="greeting">Customize Your Plan</div>
              <div className="text-sm">Make any adjustments or customizations to the AI-generated itinerary as needed.</div>
            </div>
            <div className="rounded-3xl  h-[9vh] px-5 pt-2 shadow hover:scale-110 transition-transform">
            <div className="text-black text-[18px]" id="greeting">Finalize and Book</div>
              <div className="text-sm">Once youre satisfied with the itinerary, finalize your travel plans</div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
